platform :ios, '11.0'
workspace 'CIFilter.io'
project 'CIFilter.io.xcodeproj'

source 'https://github.com/CocoaPods/Specs'

def shared_pods
  pod 'ReactiveLists', '~> 0.3.0'
  pod 'YLTableView', '~> 2.2.0', :modular_headers => true
  pod 'AloeStackView', '~> 1.0.1'
  pod 'RxAtomic', '~> 4.4.0', :modular_headers => true
  pod 'RxSwift', '~> 4.4.0', :modular_headers => true
  pod 'RxCocoa', '~> 4.4.0', :modular_headers => true
  pod 'RxGesture', '~> 2.1.0', :modular_headers => true
  pod 'IQKeyboardManagerSwift', '~> 6.2.0'
end

target 'CIFilter.io' do
  shared_pods
end

target 'CIFilter.ioTests' do
  shared_pods
end
