platform :ios, '11.0'
workspace 'CIFilter.io'
project 'CIFilter.io.xcodeproj'

source 'https://github.com/CocoaPods/Specs'

def shared_pods
  pod 'ReactiveLists', '~> 0.3.0'
end

target 'CIFilter.io' do
  shared_pods
end
