platform :ios, '13.0'
workspace 'CIFilter.io'
project 'CIFilter.io.xcodeproj'

source 'https://github.com/CocoaPods/Specs'

use_frameworks!

def shared_pods
  pod 'ReactiveLists', '~> 0.6.0'
  pod 'AloeStackView', '~> 1.0.1'
  pod 'IQKeyboardManagerSwift', '~> 6.5.4'
  pod 'Sentry', '~> 4.4.3', :modular_headers => true
  pod 'Mixpanel-swift', '~> 2.5.9'
end

target 'CIFilter.io' do
  plugin 'cocoapods-keys', {
    :project => "CIFilter.io",
    :keys => [
      "SENTRY_DSN"
    ]}

  shared_pods
end

target 'CIFilter.ioTests' do
  shared_pods
end
